#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# The pre-nginx half of the WEB_* mapping. init-nginx/dependencies.d/
# init-handbrake-web orders it before the base's init-nginx, which bakes
# $FILE_MANAGER_PATH into /etc/nginx/sites-available/default and deletes the
# files{} block when SELKIES_FILE_TRANSFERS has no "download".
# dependencies.d/init-os-end keeps it after init-adduser has remapped abc to
# PUID/PGID.
exec /usr/local/bin/handbrake-web.sh pre-nginx
